### PR TITLE
Resources: options to exclude some actions & formatted paths + nested paths

### PR DESCRIPTION
**Pull request by kreopt**
First option allows to exclude some actions and urls with format from generated routes. For example I need REST API consist only of CRUD methods but not new & edit HTML pages so I can exclude it from resource by passing exclude=['new', 'edit'] option. Also I don't need {.format} urls so generate-formatted option was introduced(True by default so it does not break current behaviour).
Third thing I need is to nest resources when introduce parent_resource: path prefix is recursively generated from parent by concatenating chain of path prefixes. For example I have such nesting: server->user->source which should be transformed to /server/:server_id/user/:user_id/source/:id (urls should be redirected to specific servers depending on server_id) and i don't want to repeatedly write /server/:server_id/user/:user_id/ prefix for all actions. So I suggest to specify 'nested' attribute into parent_resource dict. It will utilize parent's path prefix.
Last change: collection parameter for resource is optional now cause usually it is just member name concatenated with 's' character to denote plurality of object.

Unfortunately I forgot to make separate commits for each of changes are made and had knew about interactive add too late. So it just one changelist

### CODE REVIEW

**Comment by bbangert** [comment]
This PR is missing:

* CHANGELOG.rst entry
* Tests to verify it works as intended
* Doc/docstring updates indicating behavior

The existing tests failed to build as well.

Are you interested in updating this so that it can be merged?

**Comment by kreopt** [comment]
Yes, I am interested in merge. I can fix these issues next week

**Comment by bbangert** [comment]
Ok, ping this issue with a comment when its ready for a review.

**Comment by bbangert** [comment]
Closing this as there's been no forward movement since last ping. Feel free to re-open when previous comments are addressed.

**Pull request closed without merging**
