### PR TITLE
Port Routes to Python 3

### PR DESCRIPTION
**Pull request by haypo**
Classifiers in setup.py are wrong: Routes does not support Python 3, there are many issues.

I ran 2to3 and then modified the patch to keep Python 2 compatibility.

### CODE REVIEW

**Comment by haypo** [comment]
> Classifiers in setup.py are wrong: Routes does not support Python 3, there are many issues.

Oh wait, I missed the fact that setup.py uses 2to3.

I checked my setup and I foud the issue in my setup. I'm using a local devpi server to cache PyPI and I build wheel packages. My problem is that "pip wheel 'Routes>=1.12.3,!=2.0'" creates a wheel package ~/.devpi/wheelhouse/Routes-2.1-py2.py3-none-any.whl: the wheel pretends to be compatible with Python 2 and Python 3, which is wrong.

Anyway, my changes make the code directly compatible with Python 2 and Python 3, so it avoids 2to3 in setup.py.

**Comment by haypo** [comment]
It looks like my patch drops Python 3.2 support. Does it matter? If you want to keep Python 3.2 compatibility, I can modify my patch to use six.u().

**Comment by bbangert** [comment]
Nope, it totally does not. I'm fine without Py 3.2 support. :)

**Comment by haypo** [comment]
Ping? Can this change be merged?

**Comment by haypo** [comment]
This issue became even more annoying with the release of pip 7 which creates a wheel cache on demand by default.

Try "pip3 install Routes" and then "pip2 install Routes".

pip3 creates a Routes-2.1-py2.py3-none-any.whl file which is supposed to be compatible with Python 2 and Python 3, but it isn't. This wheel package was created by Python 3 which ran 2to3, so it doesn't support Python 2 anymore.

Then pip2 installs the wheel package which is only compatible with Python 3, whereas pip2 is for Python 2...

So please fix merged this patch, or fix setup.py to not create universal wheel packages: the commit 745a9207d9e48e309e292172543bc21075e65e09 broke Python 3 compatibility.

**Comment by haypo** [comment]
Ping? This issue blocks me to port the OpenStack Glance projet to Python 3.

**Comment by bbangert** [comment]
Can you remove Python 3.2 from the .travis.yml? I'm fine dropping support for 3.2, then the travis build should pass and I'll merge.

**Comment by haypo** [comment]
> Can you remove Python 3.2 from the .travis.yml?

Ok, done.

When the patch will be merged, will it be possible to release a new version of Routes?

**Comment by bbangert** [comment]
Yup!

**Comment by haypo** [comment]
Thank you! Keep me in touch when a new version is released. At least, nosetests-3.4 pass on my PC.

**Comment by haypo** [comment]
Ping for the release.

**Pull request merged**
